#!/bin/bash

cd /Users/mac/Documents/AVR/chaotron_441/firmware 

avr-gcc -Wall -Os -mmcu=attiny441 -c test.c -o test.o
avr-gcc -Wall -Os -mmcu=attiny441 -o test.elf test.o
#avr-gcc -Wall -Os -DF_CPU=8000000 -mmcu=atmega8 -c main.c -o main.o
#avr-gcc -Wall -Os -DF_CPU=8000000 -mmcu=atmega8 -o main.elf main.o

rm -f main.hex
avr-objcopy -j .text -j .data -O ihex test.elf test.hex

sleep 2
